#! /bin/bash

name=$(whoami)
date=$(date)
TODAY=$(date "+%Y-%m-%d")


option1() {
	zip -r "/WebBackups/backup_Intranet.$(date +"%m-%d-%Y").zip" /var/www/html/Intranet
	zip -r "/WebBackups/backup_Live.$(date +"%m-%d-%Y").zip" /var/www/html/Live
}

#option2() {
#	find "$source" -type f -newermt "$TODAY_START" -exec sudo cp --parents {} "$destination"  \;
#}

option3() {
	sudo cp -r -u /var/www/html/Intranet/* /var/www/html/Live
	echo "loop entered"
}

option4() {
	sudo ausearch -f /var/www/html/Intranet/ > /WebBackups/AuditLog.txt | aureport -f -i > /WebBackups/Report_on_Intranet.txt
}



while [ 1 == 1 ]
do

	echo "***** Menu *****"
	echo "Choose one of these options: "
	echo "1) Who am I and am I logged in?"
	echo "2) Backup a folder and store it as a zip"
	echo "3) Copy content from Intranet to Live, content modified: $TODAY"
	echo "4) Display a log of changes to Intranet"
	echo "5) Exit the script"

	read userInput

	case $userInput in
		1) echo "Hello $name. You are currently logged in";;
		2) option1;;
		3) option3;;
		4) option4;;
		5) exit;;
	esac
done