#! /bin/bash

name=$(whoami)
date=$(date)
TODAY=$(date "+%Y-%m-%d")
GROUPNAME="live_group"
DIRPATH="/var/www/html/Live/"

option1() {
	zip -r "/WebBackups/backup_Intranet.$(date +"%m-%d-%Y").zip" /var/www/html/Intranet
	zip -r "/WebBackups/backup_Live.$(date +"%m-%d-%Y").zip" /var/www/html/Live
}

#option2() {
#	find "$source" -type f -newermt "$TODAY_START" -exec sudo cp --parents {} "$destination"  \;
#}

option3() {
	sudo cp -r -u /var/www/html/Intranet/* /var/www/html/Live
	echo "loop entered"
}

option4() {
	sudo ausearch -f /var/www/html/Intranet/ | aureport -f -i > /WebBackups/reportOnIntranet.txt.$(date +"%m-%d-%Y")
}

option5() {
	add_user_to_group() {
    	read -p "Enter the username: " username

		# Check if the user exists
        if id "$username"; then
            echo "User '$username' already exists."
        else
            echo "User '$username' does not exist. Creating user ..."
            sudo useradd -m -s /bin/bash "$username"
        	sudo passwd "$username"
			echo "User '$username' created successfully."
        fi

    	sudo usermod -aG "$GROUPNAME" "$username"
        echo "User '$username' added to group '$GROUPNAME'."

        # Grant group ownership and permissions on the directory
        sudo chgrp -R "$GROUPNAME" "$DIRPATH"
        sudo chmod -R g+rwX "$DIRPATH"
        echo "Directory '$DIRPATH' is now accessible to group '$GROUPNAME'."
	}
	add_user_to_group
}


while [ 1 == 1 ]
do

	echo "***** Menu *****"
	echo "Choose one of these options: "
	echo "1) Who am I and am I logged in?"
	echo "2) Backup a folder and store it as a zip"
	echo "3) Copy content from Intranet to Live, content modified: $TODAY"
	echo "4) Display a log of changes to Intranet"
	echo "5) Add a user to the Live group to make immediate changes"
	echo "6) Exit the script"

	read userInput

	case $userInput in
		1) echo "Hello $name. You are currently logged in";;
		2) option1;;
		3) option3;;
		4) option4;;
		5) option5;;
		6) exit;;
	esac
done